Bug fixes
sdsmdg/trianglify pull request #24
Opened 2017-05-14 07:20 UTC by dakshitagrawal97

This PR fixes #19 and #22.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if(isChecked || trianglifyView.isFillTriangle()){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if(isChecked || trianglifyView.isFillTriangle()){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: 'else' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if(isChecked || trianglifyView.isDrawStrokeEnabled()){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if(isChecked || trianglifyView.isDrawStrokeEnabled()){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: 'else' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }else{
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +    int justColor = 0;
\[Checkstyle\] ERROR: Variable 'justColor' explicitly initialized to '0' \(default value for its type\)\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +    int justColor = 0;
\[Checkstyle\] ERROR: Variable 'justColor' must be private and have accessor methods\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +        if(justColor == 0){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +        if(justColor == 0){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +        }else if(justColor == 1){
\[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +        }else if(justColor == 1){
\[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +        }else if(justColor == 1){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +        }else if(justColor == 1){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    int flagForChangeInRelatedParameters = -2;
\[Checkstyle\] ERROR: Variable 'flagForChangeInRelatedParameters' must be private and have accessor methods\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(flagForChangeInRelatedParameters == 0)  {
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        }else if( flagForChangeInRelatedParameters == -1) {
\[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        }else if( flagForChangeInRelatedParameters == -1) {
\[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        }else if( flagForChangeInRelatedParameters == -1) {
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        }
\[Checkstyle\] ERROR: '\}' at column 9 should be on the same line as the next part of a multi\-block statement\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        else if(flagForChangeInRelatedParameters == 2){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:11 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        else if(flagForChangeInRelatedParameters == 2){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +import android.util.Log;
\[Checkstyle\] ERROR: Unused import \- android\.util\.Log\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if(this.flagForChangeInRelatedParameters != 1){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        } else if(flagForChangeInRelatedParameters == 2) {
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        } else if(flagForChangeInRelatedParameters == 1 || flagForChangeInRelatedParameters == -2) {
\[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

2017-05-18 07:30 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    void generateNewColoredSoupAndInvalidate(Canvas canvas){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 08:44 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    public void updateView(){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-18 08:59 UTC, suyashmahar reviewed
Fix these changes

2017-05-18 08:59 UTC, suyashmahar commented on README.md
> +> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect. To invalidate TrianglifyView call invalidate method on the Trianglify View Instance.
method to invalidate view for any changes to take effect is generateAndInvalidate

2017-05-18 08:59 UTC, suyashmahar commented on README.md
> +> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect. To invalidate TrianglifyView call invalidate method on the Trianglify View Instance.
Add behavioral description of following here or in a new point
* `invalidate`
* `generateAndInvalidate`

2017-05-18 08:59 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                trianglifyView.invalidate();
Why is cell size seek bar just invalidating the view? it should call `generateAndInvalidate`

2017-05-18 08:59 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    private int flagForChangeInRelatedParameters = -2;
Use integers or enum instead:
```java
public static final int TRIANGULATION_NULL = 0;
public static final int TRIANGULATION_UNCHANGED = 1;
.
.
.
```

2017-05-18 08:59 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    private int flagForChangeInRelatedParameters = -2;
Also add a note before that to describe why this flag is required

2017-05-18 08:59 UTC, suyashmahar commented on README.md
> +> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect. To invalidate TrianglifyView call updateView method on the Trianglify View Instance.
Method to invalidate view for any changes to take effect is generateAndInvalidate

Add behavioral description of following here or in a new point
* `invalidate`
* `generateAndInvalidate`

2017-05-18 08:59 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                trianglifyView.updateView();
Why is cell size seek bar just invalidating the view? it should call `generateAndInvalidate`

2017-05-18 11:12 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                trianglifyView.updateView();
it is calling the updateView() method. There it compares the flag, sees that it is 1, and hence calls generateAndInvalidate(). It can be called directly, but I have used updateView() so that there is uniformity in calling and one method to take care of all changes.

2017-05-18 11:13 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    private int flagForChangeInRelatedParameters = -2;
Yes, I will update the documentation.

2017-05-18 13:53 UTC, suyashmahar requested changes
Rest looks good

2017-05-18 13:53 UTC, suyashmahar commented on README.md
> +
`updateView` is a bit vague name, rename it to `smartUpdate` or something similar

Also update this part to explain exact difference and working, as: 

---------------------------------------------

### 2.7 Updating the View

Trianglify view can be update using two methods : 
#### Smart updating of view using `smartUpdate`
smartUpdate update view smartly, it checks for the changes in parameters from last update and decides accordingly what parts of view should be updated. More formal description is:
> Add complete description of updateView method, what changes when kind of
#### Complete regeneration using  `generateAndInvalidate`
 It regenerates everything from scratch (elaborate this point a bit more)

### (basic) Performance comparision of both method
.
.
.


Change headings and content according to your taste, but make content more descriptive and complete, so that someone who will use this does not get frustrated figuring out what it does

2017-05-18 13:53 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java
> +    private int justColor;
`justColor` is a vague term, rename it to something meaningful

2017-05-18 13:53 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    private int flagForChangeInRelatedParameters = -2;
Use enum for flags
something like:
```java
public enum ParameterChange {
    NULL_TRIANGULATION,
    UNCHANGED_TRIANGULATION,
.
.
.
}

and use them instead of numbers, numbers are confusing
```

2017-05-18 13:53 UTC, suyashmahar commented on README.md
> +
In short be more descriptive when writing about API

2017-05-19 08:26 UTC, suyashmahar approved these changes
Great work

2017-05-19 08:27 UTC, merged