Custom Palette Feature
sdsmdg/trianglify pull request #33
Opened 2017-05-21 09:53 UTC by dakshitagrawal97

This PR adds the Custom Palette Feature to the demo app. It has a separate button to go to a custom palette picker, which provides the option of selecting the suitable colors and setting it as the custom palette. On the main view, whenever the triangulation is to be colorized with the custom palette, the Custom Palette Checkbox can be ticked.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            default:
\[Checkstyle\] ERROR: Fall through from previous branch of the switch statement\.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
\[Checkstyle\] ERROR: '\-' is not preceded with whitespace\.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
\[Checkstyle\] ERROR: '\-' is not followed by whitespace\.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                startActivityForResult(customPalettePickerIntent,1);
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-21 09:57 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if ( customPaletteCheckbox.isChecked()) {
\[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            default:
\[Checkstyle\] ERROR: Fall through from previous branch of the switch statement\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
\[Checkstyle\] ERROR: '\-' is not preceded with whitespace\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
\[Checkstyle\] ERROR: '\-' is not followed by whitespace\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                startActivityForResult(customPalettePickerIntent,1);
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-21 11:36 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if ( customPaletteCheckbox.isChecked()) {
\[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            default:
\[Checkstyle\] ERROR: Fall through from previous branch of the switch statement\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
\[Checkstyle\] ERROR: '\-' is not preceded with whitespace\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
\[Checkstyle\] ERROR: '\-' is not followed by whitespace\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                startActivityForResult(customPalettePickerIntent,1);
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-21 12:40 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if ( customPaletteCheckbox.isChecked()) {
\[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

2017-05-21 12:40 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    boolean fillViewCompletely;
\[Checkstyle\] ERROR: Variable 'fillViewCompletely' must be private and have accessor methods\.

2017-05-21 12:40 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    public void checkViewFilledCompletely(){
\[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

2017-05-21 18:38 UTC, suyashmahar requested changes
Always update documentation along with development, catching up with the development would be difficult later.

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +    private ImageView c8;
Remove individual declaration of ImageViews instead declare an array of ImageView and then intialize corresponding objects using a for loop and something like `item.setThumbnailID(activity.getResources().getIdentifier(imageName, "drawable", activity.getPackageName()));` to get id of ImageView, since alll the imageViews are numbered. 

Code should not contain individual ImageView use just arrays, everu operation can be performed using for loop

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +                R.id.custom_palette_c6, R.id.custom_palette_c7, R.id.custom_palette_c8};
use for loop  to initialize these

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +                onBackPressed();
Shouldn't there be a break statement?

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
Use something like [this](http://stackoverflow.com/questions/4433790/naming-convention-for-passing-data-through-extras-in-android) instead of hard coding `"Palette Color Array"`

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/res/drawable/color_picked_imageview_border.xml
> +</shape>
no LF at end of file

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/res/drawable/ok_icon.xml
> +</vector>
no LF at end of file

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/res/drawable/palette_icon.xml
> +</vector>
no LF at end of file

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/res/values/styles.xml
> +        <item name="colorPrimaryDark">#00796B</item>
Why are colors hardcoded?

2017-05-21 18:38 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +            if ( Palette.getPalette(i).getColors()[8] == palette.getColors()[8] ) {
ye kyun?

2017-05-21 18:38 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if ( fillViewCompletely ) {
pure code base mein `if (` ke baad space nahi eisa karne se code inconsistent ho jayega

2017-05-21 18:38 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
>          }finally {
space before finally

2017-05-21 18:38 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    public boolean isFillViewCompletely() {
Is saab ko document kyun nahi kara?

2017-05-21 18:38 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int) (seed % mod);
(int) ke baad space nahi hona chahiye

2017-05-21 18:38 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +                return new Palette(0xffa50026, 0xffd73027, 0xfff46d43, 0xfffdae61, 0xfffee08b, 0xffffffbf, 0xffd9ef8b, 0xffa6d96a, 0xff66bd63);
All logic earlier implemented assumes no alpha channel is present in colors, it would break previous code

2017-05-21 18:38 UTC, suyashmahar commented on build.gradle
> +        maven { url "https://jitpack.io" }
Why this?

2017-05-21 18:38 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                if ( customPaletteCheckbox.isChecked()) {
`( custom...` no space should be there

2017-05-21 18:43 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +    private ImageView c8;
done in commit#c77efe3

2017-05-21 18:44 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +    private ImageView c8;
ok

2017-05-21 18:44 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +                onBackPressed();
yeah.

2017-05-21 18:46 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +                return new Palette(0xffa50026, 0xffd73027, 0xfff46d43, 0xfffdae61, 0xfffee08b, 0xffffffbf, 0xffd9ef8b, 0xffa6d96a, 0xff66bd63);
I will see if there is another way.

2017-05-21 18:46 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +            if ( Palette.getPalette(i).getColors()[8] == palette.getColors()[8] ) {
the last color of each palette is different. So less comparison.

2017-05-21 18:47 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        if ( fillViewCompletely ) {
👍

2017-05-21 18:47 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    public boolean isFillViewCompletely() {
Once the code is finalized, then I will do it.

2017-05-21 18:48 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int) (seed % mod);
ok

2017-05-21 18:48 UTC, dakshitagrawal97 commented on build.gradle
> +        maven { url "https://jitpack.io" }
required for colorpicker

2017-05-21 18:55 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
👍

2017-05-22 02:33 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +            if ( Palette.getPalette(i).getColors()[8] == palette.getColors()[8] ) {
Should comment on such code which use different logic than what is obvious, moreover this thing can break if any two color has same last color in future. Also just three of the colors are repeated as first colors in palette, won't make any significant difference in performance. Most of the time is spent on triangulatiion which is >> time spent on coloring

2017-05-22 02:34 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +    public boolean isFillViewCompletely() {
+1

2017-05-22 07:11 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
N/A

2017-05-22 11:50 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            int resID = getResources().getIdentifier(imageViewNumber,"id",getPackageName());
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-22 11:50 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            int resID = getResources().getIdentifier(imageViewNumber,"id",getPackageName());
\[Checkstyle\] ERROR: ',' is not followed by whitespace\.

2017-05-22 11:50 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-22 11:50 UTC, sputnikci commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int)(seed % mod);
\[Checkstyle\] ERROR: 'typecast' is not followed by whitespace\.

2017-05-22 11:51 UTC, dakshitagrawal97 commented on app/src/main/res/drawable/color_picked_imageview_border.xml
> +</shape>
done

2017-05-22 11:51 UTC, dakshitagrawal97 commented on app/src/main/res/drawable/ok_icon.xml
> +</vector>
done

2017-05-22 11:52 UTC, dakshitagrawal97 commented on app/src/main/res/drawable/palette_icon.xml
> +</vector>
done

2017-05-22 11:52 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +                return new Palette(0xffa50026, 0xffd73027, 0xfff46d43, 0xfffdae61, 0xfffee08b, 0xffffffbf, 0xffd9ef8b, 0xffa6d96a, 0xff66bd63);
not done

2017-05-22 11:52 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
N/A

2017-05-22 12:03 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int)(seed % mod);
@suyashmahar http://www.oracle.com/technetwork/java/codeconventions-150003.pdf

2017-05-22 12:03 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int)(seed % mod);
just looked it up 😅

2017-05-22 13:02 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            int resID = getResources().getIdentifier(imageViewNumber,"id",getPackageName());
@dakshitagrawal97 ^

2017-05-22 13:40 UTC, suyashmahar requested changes

2017-05-22 13:40 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java
> +                return new Palette(0xffa50026, 0xffd73027, 0xfff46d43, 0xfffdae61, 0xfffee08b, 0xffffffbf, 0xffd9ef8b, 0xffa6d96a, 0xff66bd63);
@dakshitagrawal97 Nahi sahi hai alpha channel ho ya na ho phir bhi kaam karega kyun ki 32 bits mein `0xff000000*2 == 0xff000000`

2017-05-22 13:40 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
>  }
No LF

2017-05-22 13:40 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        } finally {
Catch this exception

2017-05-22 13:40 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
>          gridHeight = height;
Why this? These things make getters and setters meaningless

2017-05-22 13:40 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
isko strings.xml ya aisi kisi global jagha define kar de, taaki ek jagha sari strings rahe aur collisions na ho

2017-05-22 13:45 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
>          gridHeight = height;
was there much before. Let me see.

2017-05-22 13:45 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
> +        } finally {
Again was there much before. I will look into it.

2017-05-23 15:23 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java
>          gridHeight = height;
I do not understand in which context you are saying. Do you mean the onSizeChanged method is unnecessary, or do you mean that I should call the gridHeight via getters?

2017-05-23 18:10 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
Not possible to define it in a static sense.

2017-05-23 18:58 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-23 18:58 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +                            .initialColor(colors[finalI]+0xff000000)
\[Checkstyle\] ERROR: '\+' is not preceded with whitespace\.

2017-05-23 18:58 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +                            .initialColor(colors[finalI]+0xff000000)
\[Checkstyle\] ERROR: '\+' is not followed by whitespace\.

2017-05-23 19:00 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int) (seed % mod);
N/A

2017-05-23 19:01 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
N/A

2017-05-24 07:05 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-24 07:06 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
N/A

2017-05-24 07:07 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
why not?

2017-05-24 07:10 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
public static final PALETTE_COLOR_ARRAY = getResources or getStrings.  Both method cannot be applied in static sense.

2017-05-24 07:11 UTC, suyashmahar commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int) (seed % mod);
Why

2017-05-24 07:15 UTC, dakshitagrawal97 commented on trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java
> +            return (int) (seed % mod);
java conventions

2017-05-24 07:16 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
Then why are you storing value form strings.xml to a variable just use it directly in the method (or with a variable with scope limited to that method)

2017-05-24 07:22 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
I have not stored any value from strings.xml
i have defined a public static final keyword to be used in intent extras as given in the example at android developers

2017-05-24 07:24 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
https://developer.android.com/training/basics/firstapp/starting-activity.html
@suyashmahar

2017-05-24 07:27 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
Oh, sorry I got confused

2017-05-24 07:29 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
But what I was saying is declaring such strings globally in project so that they can be accessed from any class. This will help in managing such strings easily, allows editing content of string without changing them at every place they are used.

2017-05-24 09:24 UTC, sputnikci commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
\[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

2017-05-24 09:29 UTC, dakshitagrawal97 commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java
> +            imageViews[i].setOnClickListener(new View.OnClickListener() {
N/A

2017-05-24 11:45 UTC, merged