Fixed issue #56
sdsmdg/trianglify pull request #59
Opened 2018-03-19 18:10 UTC by s4mr4t

2018-03-19 18:23 UTC, suyashmahar requested changes
Please upload an apk to drive and share a link here.

2018-03-19 18:23 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
>      public static final String PALETTE_COLOR_ARRAY = "Palette Color Array";
Please move this to `strings.xml`.

2018-03-19 18:23 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +        if (ContextCompat.checkSelfPermission(this,
Nitpicking but something like the following would greatly increase readability:
```java
boolean permissionStatus = 
    ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE);
if (permissionStatus != ...) {
```

2018-03-20 06:23 UTC, s4mr4t commented
APK: https://goo.gl/AjBeMV

2018-03-20 15:16 UTC, merged