Added a better saving method
sdsmdg/trianglify pull request #60
Opened 2018-03-23 14:58 UTC by r1walz

Save better quality PNGs using output stream. Previously we were using insertImage to save the image to the gallery.

2018-03-23 17:17 UTC, suyashmahar requested changes
Nice work @r1walz, just fix these and we'll be good to merge this.

2018-03-23 17:17 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }
Catch this exception with an error message, toast notification would do, without one user won't know what went wrong.

2018-03-23 17:17 UTC, suyashmahar commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +
This one too

2018-03-23 17:19 UTC, suyashmahar commented
@r1walz One last thing, please upload an apk here when you make these changes.

2018-03-23 23:41 UTC, r1walz commented
https://goo.gl/AjBeMV
Added a toast message to help the user identify the error.

2018-03-24 23:57 UTC, r1walz commented on app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java
> +                }
should I just Toast out e.getMessage()?

2018-03-26 13:06 UTC, suyashmahar approved these changes

2018-03-26 14:44 UTC, merged